import { Product, Review, BannerSlide } from './types';

export const CATEGORIES = [
  { id: 'all', name: 'All Products', icon: 'ShoppingBag', count: 18, desc: 'Explore our full premium catalog' },
  { id: 'bedsheet', name: 'Bedsheets', icon: 'Bed', count: 4, desc: 'Luxury non-allergenic cotton bedsheets' },
  { id: 'cloth-men-women', name: 'Cloth Men and Women', icon: 'User', count: 4, desc: 'Premium custom stitched collections' },
  { id: 'electronic-gadgets', name: 'Electronic & Gadgets', icon: 'Smartphone', count: 4, desc: 'Cool devices & everyday smart gadgets' },
  { id: 'kitchen-accessories', name: 'Kitchen Accessories', icon: 'ChefHat', count: 3, desc: 'Practical & elegant kitchen utensils' },
  { id: 'water-bottles', name: 'Water Bottles', icon: 'GlassWater', count: 3, desc: 'Double-walled insulated steel flasks' }
];

export const COLLECTIONS = [
  { id: 'bedsheet', name: 'Bedsheets', image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=300' },
  { id: 'cloth-men-women', name: 'Cloth Men and Women', image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=80&w=300' },
  { id: 'electronic-gadgets', name: 'Electronic & Gadgets', image: 'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&q=80&w=300' },
  { id: 'kitchen-accessories', name: 'Kitchen Accessories', image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=300' },
  { id: 'water-bottles', name: 'Water Bottles', image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=300' }
];

export const PAKISTAN_CITIES = [
  'Karachi', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Gujranwala', 
  'Peshawar', 'Multan', 'Hyderabad', 'Islamabad', 'Quetta', 
  'Sargodha', 'Sialkot', 'Bahawalpur', 'Sukkur', 'Jhang', 
  'Shekhupura', 'Mardan', 'Gujrat', 'Larkana', 'Kasur'
];

export const PRODUCTS: Product[] = [
  // --- BEDSHEETS ---
  {
    id: 'luxury-cotton-bedsheet',
    name: 'Premium Cotton Double Bedsheet Set',
    price: 2450,
    originalPrice: 3500,
    description: 'High-thread-count premium pure cotton double bedsheet set with two matching pillow covers.',
    longDescription: 'Treat your master bed to ultimate soft comfort. Made from 100% combed organic long-staple cotton, this luxury bedsheet features a smooth, cooling finish designed to withstand infinite washing cycles without color fading. Includes one double bedsheet and two elegant standard size pillowcases.',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=600',
      'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=600'
    ],
    rating: 4.9,
    reviewsCount: 184,
    category: 'bedsheet',
    features: ['100% Pure Long-Staple Cotton', 'Includes 2 matching pillow cases', 'Hypoallergenic and highly breathable', 'Fast-dyed color warranty'],
    variants: ['Classic White', 'Soft Charcoal Grey', 'Sand Beige'],
    sizes: ['Double King Size', 'Queen Size'],
    stock: 40,
    badge: '-30%'
  },
  {
    id: 'floral-garden-bedsheet',
    name: 'Floral Garden Queen Bedsheet',
    price: 1950,
    originalPrice: 2800,
    description: 'Delightful pastel floral pattern queen bedsheet designed to bring botanical charm to your room.',
    longDescription: 'Bring fresh summer vibes into your home! Crafted with extra soft lightweight luxury micro-cotton, this stunning queen bedsheet comes adorned with elegant hand-painted style watercolor botanicals. Stays wrinkle-free all day long.',
    image: 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 112,
    category: 'bedsheet',
    features: ['Cooling Micro-Cotton luxury fabric', 'Wrinkle-resistant easy care finish', 'Strong double stitched hems', 'Elegant floral aesthetics'],
    variants: ['Blush Rose Pink', 'Soft Lavender Purple'],
    sizes: ['Queen Size'],
    stock: 25,
    badge: 'Popular'
  },
  {
    id: 'kids-cartoon-bedsheet',
    name: 'Kids Soft Cartoon Single Bedsheet',
    price: 1850,
    originalPrice: 2600,
    description: 'Playful and bright cotton single bedsheet set for kids rooms, featuring lovely animal prints.',
    longDescription: 'Ensure sweet dreams for your little ones! This kids single bedsheet set features non-toxic organic dye prints of cute woodland forest animals. Made of buttery-soft combed cotton weave that prevents skin allergies or irritation.',
    image: 'https://images.unsplash.com/photo-1531835551805-16d864c8d311?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 65,
    category: 'bedsheet',
    features: ['Eco-Secure baby safe organic dyes', 'Made of 100% combed cotton', 'Includes 1 cute animal print pillowcase', 'Perfect fit deep corners'],
    variants: ['Woodland Forest Sage', 'Space Galaxy Blue'],
    sizes: ['Single Bed Size'],
    stock: 35,
    badge: '-30%'
  },
  {
    id: 'geometric-sateen-bedsheet',
    name: 'Geometric Sateen King Bedsheet Set',
    price: 2999,
    originalPrice: 4200,
    description: 'Dazzling ultra-luxury sateen weave bedsheet featuring elegant charcoal geometric prints.',
    longDescription: 'Add a touch of absolute sophistication to your guest room or master suite. Woven from luxury sateen cotton with an ultra-soft sheen and velvety smooth texture. Resists dust mites and offers premium comfort.',
    image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&q=80&w=600',
    rating: 5.0,
    reviewsCount: 41,
    category: 'bedsheet',
    features: ['Luxury Sateen finish weave', 'Wrinkle-resistant heavy thread count', 'Includes 2 geometric print pillowcases', 'Stunning modern geometric prints'],
    variants: ['Charcoal Geometric', 'Navy Gold Geometric'],
    sizes: ['Double King Size'],
    stock: 15,
    badge: 'Premium'
  },
  {
    id: 'royal-velvet-bedsheet',
    name: 'Royal Velvet Embossed King Bedsheet',
    price: 3499,
    originalPrice: 4800,
    description: 'Ultra-luxurious soft touch embossed velvet king-size bedsheet set with beautiful lace-lined borders.',
    longDescription: 'Experience imperial luxury right in your bedroom. This premium heavy embossed velvet bedsheet offers supreme warmth and an incredibly plush, silky feel. Perfect for bridal gifting or elegant winter setups. Includes 1 king sheet, 2 pillow covers, and 1 cushion cover.',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 38,
    category: 'bedsheet',
    features: ['Premium heavy velvet fabric', 'Beautiful luxury embossed self-design', 'Includes matching cushion cover & 2 pillowcases', 'Perfect warm luxury look'],
    variants: ['Royal Maroon', 'Plush Navy Blue', 'Elegant Rose Gold'],
    sizes: ['Double King Size'],
    stock: 12,
    badge: 'Luxury'
  },
  {
    id: 'classic-stripe-bedsheet',
    name: 'Classic Hotel Stripe King Bedsheet',
    price: 2250,
    originalPrice: 3200,
    description: 'Luxury hotel quality satin stripe cotton bedsheet set, extremely soft and durable.',
    longDescription: 'Bring the signature luxury of 5-star hotels home. Woven with exquisite combed cotton satin stripes, this sheet provides excellent cooling, sweat absorption, and a wonderfully crisp texture. Stays perfectly in place with heavy-duty elastic corners.',
    image: 'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 57,
    category: 'bedsheet',
    features: ['5-Star Hotel grade combed cotton', 'Exquisite satin stripes weave', 'Highly breathable and cooling', 'Includes 2 striped pillow covers'],
    variants: ['Snow White', 'Ice Blue', 'Pearl Grey'],
    sizes: ['Double King Size', 'Queen Size'],
    stock: 20,
    badge: 'Hotel Grade'
  },
  {
    id: 'embroidered-bridal-bedsheet',
    name: 'Embroidered Luxury Bridal Bedsheet Set',
    price: 4499,
    originalPrice: 6500,
    description: 'Breathtaking heavy silk-embroidered bridal king size bedsheet with matching pillowcases & cushion covers.',
    longDescription: 'Our signature bridal collection sheet is stitched with ultimate precision. It features beautiful heavy floral tilla and silk embroidery along the borders and pillow accents. Includes 1 King sheet, 2 Embroidered pillowcases, 2 Textured cushion covers, and 1 pristine bolster cover.',
    image: 'https://images.unsplash.com/photo-1631679706909-1844bbd07221?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 46,
    category: 'bedsheet',
    features: ['Premium Silk-Cotton blend fabric', 'Exquisite heavy border embroidery', 'Perfect luxury look for weddings', 'Includes 5 matching pillow/cushion cases'],
    variants: ['Golden Ivory', 'Royal Crimson Red', 'Muted Plum'],
    sizes: ['Double King Size'],
    stock: 8,
    badge: 'Bridal Luxe'
  },
  {
    id: 'boho-mandala-bedsheet',
    name: 'Bohemian Mandala Cotton Bedsheet',
    price: 1999,
    originalPrice: 2800,
    description: 'Chic bohemian styled mandala print luxury cotton double bedsheet with matching cushion cases.',
    longDescription: 'Bring positive, artistic energy to your bedroom. Features premium organic long-staple cotton printed with safe organic vegetable dyes in beautiful geometric boho mandala patterns. Feels incredibly smooth on the skin and brightens up any interior instantly.',
    image: 'https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 32,
    category: 'bedsheet',
    features: ['100% Pure Organic Cotton', 'Eco-friendly non-toxic vegetable dyes', 'Super-soft combed cotton touch', 'Includes 2 matching printed pillow covers'],
    variants: ['Turquoise Sunset', 'Earthy Mustard', 'Monochrome Charcoal'],
    sizes: ['Double King Size', 'Single Bed Size'],
    stock: 18,
    badge: '100% Cotton'
  },
  {
    id: 'soft-flannel-bedsheet',
    name: 'Cozy Flannel Thermal Winter Bedsheet',
    price: 2799,
    originalPrice: 3800,
    description: 'Super warm brushed flannel cotton thermal bedsheet set, designed for cold winter nights.',
    longDescription: 'Stay incredibly cozy and warm during breezy cold winter nights. Made of high-grade double brushed heavy flannel cotton that locks in body warmth while remaining completely breathable. Soft fuzzy texture feels amazing to cuddle in.',
    image: 'https://images.unsplash.com/photo-1505693395321-883724634266?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 29,
    category: 'bedsheet',
    features: ['Double-brushed heavy thermal flannel', 'Locks in warmth efficiently', 'Anti-pilling velvet texture treatment', 'Includes 2 warm fuzzy pillowcases'],
    variants: ['Alpine Red Plaid', 'Silver Grey Pine', 'Winter Navy Star'],
    sizes: ['Double King Size'],
    stock: 14,
    badge: 'Winter Cozy'
  },

  // --- CLOTH MEN & WOMEN ---
  {
    id: 'mens-cotton-kurta',
    name: 'Mens Premium Cotton Stitched Kurta',
    price: 2150,
    originalPrice: 3200,
    description: 'Designer stitched solid cotton kurta with premium band collar and classic button placket.',
    longDescription: 'Stay sharp and comfortable at formal gatherings or daily wear. Woven from 100% premium Pakistani cotton yarn, this classic Kurta offers structured shoulders, a clean band collar, subtle embroidery detailing around the placket, and functional side pockets.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 135,
    category: 'cloth-men-women',
    features: ['100% Soft Structured Cotton', 'Intricate designer collar stitching', 'Dual side pockets', 'Breezy breathable summer wear'],
    variants: ['Midnight Navy Blue', 'Elegant Royal Off-White', 'Slate Charcoal Grey'],
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    stock: 50,
    badge: 'Best Seller'
  },
  {
    id: 'womens-linen-3piece',
    name: 'Womens Designer Linen 3-Piece Suit',
    price: 3850,
    originalPrice: 5500,
    description: 'Fully stitched luxury linen 3-piece suit with heavy embroidered shirt and matching dupatta.',
    longDescription: 'The perfect festive & luxury ensemble. Features a stunning premium linen shirt embellished with rich detailed neckline embroidery. Paired with comfortable loose-fitting matching linen trousers and a premium digital printed light chiffon dupatta.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 96,
    category: 'cloth-men-women',
    features: ['Premium Quality Soft Linen Shirt', 'Matching custom straight linen trousers', 'High-definition printed chiffon dupatta', 'No shrink guarantee'],
    variants: ['Mustard Gold Flower', 'Emerald Green Leaf'],
    sizes: ['Small', 'Medium', 'Large'],
    stock: 22,
    badge: '-30%'
  },
  {
    id: 'mens-casual-linen-shirt',
    name: 'Mens Casual Breathable Linen Shirt',
    price: 1750,
    originalPrice: 2500,
    description: 'Breezy spread collar pure linen shirt for men, perfect for smart casual styling.',
    longDescription: 'Upgrade your summer wardrobe. This premium casual shirt is crafted in lightweight flax linen blended with combed cotton for optimal smoothness and minimum wrinkles. Styled with adjustable long sleeves and a curved hem.',
    image: 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 88,
    category: 'cloth-men-women',
    features: ['Premium flax linen-cotton blend', 'Classic smart spread collar', 'Adjustable roll-up sleeves', 'Cool touch active fiber'],
    variants: ['Pastel Sage Green', 'Soft Sky Blue', 'Classic White'],
    sizes: ['Small', 'Medium', 'Large', 'X-Large'],
    stock: 30,
    badge: 'Popular'
  },
  {
    id: 'womens-cotton-kurtis',
    name: 'Womens Summer Cotton Printed Kurti',
    price: 1450,
    originalPrice: 2100,
    description: 'Charming pastel lawn cotton printed kurti with lovely lace border highlights.',
    longDescription: 'Simple, chic, and lightweight. This stitched lawn cotton kurti is covered with delicate block prints and finished with exquisite custom lace detailing at the sleeves and daman. Ideal for colleges, work, and outdoor strolls.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 74,
    category: 'cloth-men-women',
    features: ['Super lightweight lawn cotton', 'Elegant lace detailed borders', 'Fast-dyed eco friendly printing', 'Highly durable stitching'],
    variants: ['Peach Bloom', 'Mint Meadow'],
    sizes: ['Small', 'Medium', 'Large'],
    stock: 45,
    badge: '-30%'
  },

  // --- ELECTRONIC & GADGETS ---
  {
    id: 'wireless-earbuds-pro',
    name: 'Ultra-Bass Wireless Earbuds Pro',
    price: 1850,
    originalPrice: 2700,
    description: 'Ergonomic wireless bluetooth earbuds with heavy bass response and smart LED power display case.',
    longDescription: 'Immerse yourself in high fidelity audio! Features powerful 13mm dynamic stereo drivers, instant bluetooth 5.3 pairing, environmental noise cancellation (ENC), up to 30 hours of continuous charging case battery, and smart touch control sensors.',
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 310,
    category: 'electronic-gadgets',
    features: ['High Fidelity stereo sound with rich deep bass', 'Intelligent LED battery indicator case', 'IPX5 sweat and splash resistance', 'Instant Bluetooth 5.3 auto pairing'],
    variants: ['Glossy Black', 'Frosty White'],
    sizes: ['One Size Fit'],
    stock: 65,
    badge: 'Best Value'
  },
  {
    id: 'smart-fitness-band',
    name: 'Waterproof Smart Fitness Tracker',
    price: 2199,
    originalPrice: 3100,
    description: 'Dynamic fitness smart band with color touch screen, heart rate monitor, and sports modes.',
    longDescription: 'Take control of your health. Track daily steps, heart rate patterns, sleep cycles, blood oxygen saturation (SpO2), and call notifications directly on your wrist. Features an extra long 14-day battery backup on a single USB charge.',
    image: 'https://images.unsplash.com/photo-1575311373937-040b8e1fd5b6?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 142,
    category: 'electronic-gadgets',
    features: ['1.1 Inch high definition color screen', 'Real-time heart rate & Sleep monitoring', 'Pedometer & Multiple Sports modes', 'Up to 14 days ultra battery life'],
    variants: ['Stealth Black', 'Ocean Navy', 'Blush Pink'],
    sizes: ['Adjustable Strap'],
    stock: 40,
    badge: '-30%'
  },
  {
    id: 'portable-mini-humidifier',
    name: 'USB Desktop Portable Mini Humidifier',
    price: 999,
    originalPrice: 1500,
    description: 'Cool mist personal desktop humidifier with auto shut-off safety and soothing 7-color LED lights.',
    longDescription: 'Breathe comfortable and fresh air. This personal mini humidifier produces highly soothing cool ultrasonic mist that hydrates skin and relieves dry throat. Holds 300ml water and runs completely silent, perfect for bedrooms and work desks.',
    image: 'https://images.unsplash.com/photo-1519183071298-a2962feb14f4?auto=format&fit=crop&q=80&w=600',
    rating: 4.6,
    reviewsCount: 95,
    category: 'electronic-gadgets',
    features: ['Ultrasonic completely quiet operation', '300ml volume auto-cutoff safety sensor', 'Lovely 7-color breathing LED light', 'Universal USB power input'],
    variants: ['Arctic White', 'Cherry Pink'],
    sizes: ['Standard 300ml'],
    stock: 50,
    badge: 'Popular'
  },
  {
    id: 'led-desk-lamp-charger',
    name: 'LED Desk Lamp with Wireless Charger',
    price: 2450,
    originalPrice: 3500,
    description: 'Flexible neck LED study desk lamp integrated with 10W rapid phone wireless charging base.',
    longDescription: 'The ultimate space saving desk companion. Features touch controls to switch between 3 color temperatures (Warm, Cool, White) and adjust brightness. Place your Qi-enabled smartphone on the non-slip base for wireless fast charging.',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 56,
    category: 'electronic-gadgets',
    features: ['10W smart wireless fast charging pad', '3 adjustable color modes & seamless dimming', 'Flexible 360 degree silicone neck', 'Eye-safe flicker free light panel'],
    variants: ['Matte Black', 'Minimalist White'],
    sizes: ['Universal Fit'],
    stock: 25,
    badge: 'New'
  },

  // --- KITCHEN ACCESSORIES ---
  {
    id: 'silicone-cooking-utensils',
    name: '12Pcs Silicone Cooking Utensils Set',
    price: 2350,
    originalPrice: 3400,
    description: 'Premium food-grade silicone kitchen cooking spoon set with elegant wooden handles.',
    longDescription: 'The comprehensive high-end kitchen makeover. Includes soup ladle, solid spoon, slotted spatula, pasta server, tongs, whisk, and more, housed in a matching holder cup. Heat-resistant up to 230C and non-scratch for premium nonstick pans.',
    image: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 154,
    category: 'kitchen-accessories',
    features: ['Food-grade FDA certified silicone', 'Non-scratch and heat-resistant to 230C', 'Premium polished wooden handles', 'Includes matching counter organizer cup'],
    variants: ['Nordic Sage Green', 'Soft Charcoal Grey', 'Cream Beige'],
    sizes: ['12-Piece Set'],
    stock: 28,
    badge: '-30%'
  },
  {
    id: 'automatic-pepper-grinder',
    name: 'Electric Automatic Pepper & Salt Grinder',
    price: 1199,
    originalPrice: 1800,
    description: 'Battery operated electric pepper and coarse salt grinder mill with adjustable coarseness knob.',
    longDescription: 'Enhance your cooking experience with absolute ease. Simply push the top button to automatically grind fresh pepper corn or sea salt crystals. Features a powerful ceramic grinding core and built-in LED light to illuminate dishes.',
    image: 'https://images.unsplash.com/photo-1588854337236-6889d631faa8?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 83,
    category: 'kitchen-accessories',
    features: ['One-touch automatic button operation', 'High-hardness premium ceramic grinding core', 'Fully adjustable bottom coarseness dial', 'Integrated soft LED indicator light'],
    variants: ['Matte Black Single', 'Brushed Stainless Steel'],
    sizes: ['Single Unit'],
    stock: 35,
    badge: 'Popular'
  },
  {
    id: 'stainless-steel-measuring-cups',
    name: 'Stainless Steel Measuring Cups & Spoons',
    price: 899,
    originalPrice: 1300,
    description: 'Heavy-duty 8-piece stainless steel measuring cups and spoons set for precise baking.',
    longDescription: 'Every baker’s dream tool! Crafted from durable, rust-proof food-grade stainless steel with soft non-slip colorful silicone handles. Engraved with easy-to-read volume measurement labels that will never fade away.',
    image: 'https://images.unsplash.com/photo-1595079676339-1534801ad6cf?auto=format&fit=crop&q=80&w=600',
    rating: 4.7,
    reviewsCount: 62,
    category: 'kitchen-accessories',
    features: ['Food-grade durable stainless steel', 'Color-coded non-slip silicone handles', 'Engraved permanent metric labels', 'Interlocking storage ring included'],
    variants: ['Rainbow Silicone Pack'],
    sizes: ['8-Piece Pack'],
    stock: 45,
    badge: '-30%'
  },

  // --- WATER BOTTLES ---
  {
    id: 'vacuum-insulated-flask',
    name: 'Double-Wall Vacuum Insulated Steel Flask',
    price: 1650,
    originalPrice: 2400,
    description: 'Premium stainless steel water flask that keeps drinks icy cold for 24 hours or hot for 12 hours.',
    longDescription: 'Stay perfectly hydrated with clean, crisp tasting drinks. Made from 18/8 professional kitchen-grade food stainless steel. Features a sweat-proof exterior matte finish and an leakproof spill-free screw cap with carrier handle loop.',
    image: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 224,
    category: 'water-bottles',
    features: ['Double-wall state-of-the-art vacuum insulation', 'Keeps cold for 24 hours, hot for 12 hours', 'Premium 18/8 food-grade steel lining', 'Leakproof heavy duty loop handle lid'],
    variants: ['Matte Black', 'Forest Green', 'Ocean Teal', 'Classic Silver'],
    sizes: ['500ml', '750ml'],
    stock: 80,
    badge: 'Best Seller'
  },
  {
    id: 'gradient-sports-bottle',
    name: 'Gradient Leak-Proof Sports Water Bottle',
    price: 999,
    originalPrice: 1500,
    description: 'Durable eco-friendly sports bottle with motivational time markers, straw, and leak-proof lid.',
    longDescription: 'Achieve your daily hydration targets. Features motivational times and volume scale labels, easy single-press pop-open lid lock, built-in soft removable silicone straw, and beautiful pastel gradient design.',
    image: 'https://images.unsplash.com/photo-1523362628745-0c100150b504?auto=format&fit=crop&q=80&w=600',
    rating: 4.8,
    reviewsCount: 110,
    category: 'water-bottles',
    features: ['Motivational time indicators & scales', '100% BPA-Free Tritan food-grade material', 'Pop-up leakproof straw click lid', 'Comfortable carrying wrist strap'],
    variants: ['Blue Pink Gradient', 'Purple Green Gradient'],
    sizes: ['1000ml'],
    stock: 55,
    badge: '-30%'
  },
  {
    id: 'kids-silicone-thermos',
    name: 'Kids Cute Silicone Thermos Water Bottle',
    price: 1299,
    originalPrice: 1900,
    description: 'Spill-proof vacuum kids thermos bottle covered with cute soft shock-absorbing silicone cartoon sleeve.',
    longDescription: 'Perfect for school lunch bags! Crafted from lightweight kitchen steel with a double insulated wall to keep water cool all day. The outer shockproof cartoon protective case prevents damage from school playground drops.',
    image: 'https://images.unsplash.com/photo-1544161515-4ab6ce6db874?auto=format&fit=crop&q=80&w=600',
    rating: 4.9,
    reviewsCount: 78,
    category: 'water-bottles',
    features: ['Unbreakable insulated stainless steel', '100% spill-proof push-button straw lid', 'Soft protective cartoon silicone skin', 'Included school shoulder strap harness'],
    variants: ['Dino Green', 'Bunny Pink', 'Space Blue'],
    sizes: ['400ml'],
    stock: 30,
    badge: 'New'
  }
];

export const REVIEWS: Review[] = [
  { id: 'rev-1', writer: 'Abdul Haseeb', rating: 5, date: 'June 18, 2026', text: 'Highly recommended! Fast delivery and exceptional packaging.' },
  { id: 'rev-2', writer: 'Ayesha Khan', rating: 5, date: 'June 20, 2026', text: 'The fabric of the bedsheets is extremely comfortable and didn\'t bleed or fade after washing!' },
  { id: 'rev-3', writer: 'Hassan Shah', rating: 5, date: 'June 23, 2026', text: 'Wireless earbuds have superb audio depth and battery lasts for days. Best customer service on WhatsApp!' }
];

export const BANNER_SLIDES: BannerSlide[] = [
  {
    id: 'slide-1',
    title: 'THE HOME & LIFE BOUTIQUE',
    subtitle: 'Premium Everyday Essentials',
    priceText: 'Direct-to-home quality, unbeatable direct factory prices 🏠',
    badge: 'BEDSHEETS • CLOTHING • COOL GADGETS & HOMEWARES',
    tagline: 'FAST COD DELIVERY • NATIONWIDE PAKISTAN SUPPORT • EASY RETURNS',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&q=80&w=1200',
    linkCategory: 'all'
  },
  {
    id: 'slide-2',
    title: 'Cozy Bedsheets Collection',
    subtitle: 'Pure Long-Staple Cotton Sheets',
    priceText: 'Starting From Rs. 1850 Only',
    badge: 'Flat 30% Off',
    tagline: 'Transform your bedroom into a five-star hotel suite with our premium double bedsheets.',
    image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?auto=format&fit=crop&q=80&w=1200',
    linkCategory: 'bedsheet'
  }
];
